/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* server.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char *fio_server_arg);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char *bind_sock);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct sockaddr_in saddr_in);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct sockaddr_in6 saddr_in6);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int use_ipv6);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int has_zlib);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int use_zlib);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char me[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static pthread_key_t sk_out_key);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char const *fio_server_ops[]);
