/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* mmap.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static long unsigned int mmap_map_size);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct ioengine_ops ioengine);
