/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* client.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct timespec eta_ts);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct flist_head client_list);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct flist_head eta_list);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct flist_head arg_list);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int sum_stat_nr);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct json_object *root);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct json_object *job_opt_object);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct json_array *clients_array);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct json_array *du_array);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int error_clients);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct flist_head client_hash[]);
