/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* time.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct timespec genesis);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static long unsigned int ns_granularity);
