/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* backend.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fio_sem *startup_sem);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct flist_head *cgroup_list);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char *cgroup_mnt);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int exit_value);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int volatile fio_abort);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int nr_process);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int nr_thread);
