/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* sync.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct ioengine_ops ioengine_rw);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct ioengine_ops ioengine_prw);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct ioengine_ops ioengine_vrw);
