/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* rate-submit.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct workqueue_ops rated_wq_ops);
