/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* init.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char **ini_file);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int max_jobs);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int dump_cmdline);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int parse_only);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct thread_data def_thread);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char **job_sections);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int nr_job_sections);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int prev_group_jobs);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char cmd_optstr[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static _Bool did_arg);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct option l_opts[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fpre_keyword fpre_keywords[]);
