/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* genzipf.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct flist_head *hash);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static long unsigned int hash_bits);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static long unsigned int hash_size);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char const *dist_types[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int dist_type);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static long unsigned int gib_size);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static long unsigned int block_size);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static long unsigned int output_nranges);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static double percentage);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static double dist_val);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static int output_type);
