/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* flow.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct flist_head *flow_list);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fio_sem *flow_lock);
