/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* dedupe.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct rb_root rb_root);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct bloom *bloom);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fio_sem *rb_lock);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int blocksize);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int num_threads);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int chunk_size);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int dump_output);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int odirect);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int collision_check);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int print_progress);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int use_bloom);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static uint64_t total_size);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static uint64_t cur_offset);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fio_sem *size_lock);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fio_file file);
