/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* net.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fio_option options[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct ioengine_ops ioengine_rw);
