/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* memcpy.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct memcpy_test tests[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct memcpy_type t[]);
