/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* prio_tree.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static long unsigned int index_bits_to_maxindex[]);
