/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* filehash.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int file_hash_size);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct flist_head *file_hash);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fio_sem *hash_lock);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct bloom *file_bloom);
