/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* eta.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char __run_str[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char run_str[]);
