/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* filesetup.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct flist_head filename_list);
