/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* options.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct pattern_fmt_desc fmt_desc[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fio_keyword fio_keywords[]);
