/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* smalloc.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct pool mp[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int nr_pools);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int last_pool);
