/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* parse.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char const *opt_type_names[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fio_option const *__fio_options);
