/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* stat.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char const *block_state_names[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static _Bool status_interval_init);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct timespec status_time);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static _Bool status_file_disabled);
