/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* idletime.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct idle_prof_common volatile ipc);
