/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* libfio.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char const *fio_os_strings[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char const *fio_arch_strings[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char const *td_runstates[]);
