/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* gettime.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static enum fio_cs fio_clock_source_inited);
