/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-fio-data.h"
/* act.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct act_pass_criteria act_pass[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct act_run_data *act_run_data);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static char const *act_opts[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int opt_idx);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static unsigned int org_idx);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct act_options act_options);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct fio_option options[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct prof_io_ops act_io_ops);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_fio, static struct profile_ops act_profile);
